export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_ONE_COUNTRY_SUCCESS = "GET_ONE_COUNTRY_SUCCESS";
export const GET_ONE_COUNTRY_LOADING = "GET_ONE_COUNTRY_LOADING";
export const GET_ONE_COUNTRY_ERROR = "GET_ONE_COUNTRY_ERROR";

export const GET_LIST_COUNTRIES_SUCCESS = "GET_LIST_COUNTRIES_SUCCESS";
export const GET_LIST_COUNTRIES_LOADING = "GET_LIST_COUNTRIES_LOADING";
export const GET_LIST_COUNTRIES_ERROR = "GET_LIST_COUNTRIES_ERROR";

export const GET_FILTER_COUNTRIES_SUCCESS = "GET_FILTER_COUNTRIES_SUCCESS";
export const GET_FILTER_COUNTRIES_LOADING = "GET_FILTER_COUNTRIES_LOADING";
export const GET_FILTER_COUNTRIES_ERROR = "GET_FILTER_COUNTRIES_ERROR";
